# bot config file

# Discord bot token. DO NOT INCLUDE THIS ANYWHERE IN YOUR DISTRIBUTED CODE!
token: '<your token goes here>'

# Database connection string and collection references
dbServer: '<server address>'
port: <port>
guildDb: '<name of your guild database>'
memberDb: '<name of your member database>'
configDb: '<name of your config database>'
version: '0.6.0-a.1'

# A list of all cogs we are loading when starting up the bot. Don't change this unless you write your own
# custom cogs or change the directory structure.
load_extensions:
    - 'ReQuest.cogs.admin'
    - 'ReQuest.cogs.config'
    - 'ReQuest.cogs.gm'
    - 'ReQuest.cogs.info'
    - 'ReQuest.cogs.player'

# Server Allowlist
allowList: False # Set true if utilizing a server allowlist.